### ISSUE TITLE
Does it work with Stripe Connect Express

### ISSUE THREAD

**Issue by dgillier** [cloudcreativity/laravel-stripe#4]
Hello,
Looks like the Seller need to have or create a stripe account on his own, my understanding is this package does not support express accounts (and the creation process) ?

Thanks for your answer !
Denis

**Comment by lindyhopchris** [comment]
Not at the moment, but we're likely to add at some point because we might switch to using Stripe Express accounts ourselves. Unfortunately I haven't had a huge amount of time available on Open Source recently and the priority has been my Laravel JSON API package. Hopefully will get to do more on this Stripe package in the future.
